# Generated by Django 5.1.4 on 2024-12-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_courses_options_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
